[package]
name = "jobs"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
agent = { workspace = true }
dispatch = { path = "../dispatch" }
serde_json = { workspace = true }
world = { path = "../world" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
